// <auto-generated />
namespace TruckTransport_Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.0-20911")]
    public sealed partial class nalog_id_nullable_u_zadaci : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(nalog_id_nullable_u_zadaci));
        
        string IMigrationMetadata.Id
        {
            get { return "201803052036260_nalog_id_nullable_u_zadaci"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
