// <auto-generated />
namespace TruckTransport_Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.0-20911")]
    public sealed partial class dodano_polje_broj_stajalista_stajalista_nalozi : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(dodano_polje_broj_stajalista_stajalista_nalozi));
        
        string IMigrationMetadata.Id
        {
            get { return "201804171608217_dodano_polje_broj_stajalista_stajalista_nalozi"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
