// <auto-generated />
namespace TruckTransport_Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.0-20911")]
    public sealed partial class izmjena_dispecer_login_lastlogin_unixtime : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(izmjena_dispecer_login_lastlogin_unixtime));
        
        string IMigrationMetadata.Id
        {
            get { return "201801271234155_izmjena_dispecer_login_lastlogin_unixtime"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
