// <auto-generated />
namespace TruckTransport_Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.0-20911")]
    public sealed partial class dodani_logirani_dogadjaji : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(dodani_logirani_dogadjaji));
        
        string IMigrationMetadata.Id
        {
            get { return "201801271142016_dodani_logirani_dogadjaji"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
