// <auto-generated />
namespace TruckTransport_Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.0-20911")]
    public sealed partial class izmjena_stajalista_nalozi_umjesto_stajalista_zadaci : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(izmjena_stajalista_nalozi_umjesto_stajalista_zadaci));
        
        string IMigrationMetadata.Id
        {
            get { return "201802031940216_izmjena_stajalista_nalozi_umjesto_stajalista_zadaci"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
